# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/luisremis/GitHub/genetics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/luisremis/GitHub/genetics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luisremis/GitHub/genetics/CMakeFiles /Users/luisremis/GitHub/genetics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luisremis/GitHub/genetics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Robot

# Build rule for target.
Robot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Robot
.PHONY : Robot

# fast build rule for target.
Robot/fast:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/build
.PHONY : Robot/fast

src/ArbolRobot.o: src/ArbolRobot.cpp.o
.PHONY : src/ArbolRobot.o

# target to build an object file
src/ArbolRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ArbolRobot.cpp.o
.PHONY : src/ArbolRobot.cpp.o

src/ArbolRobot.i: src/ArbolRobot.cpp.i
.PHONY : src/ArbolRobot.i

# target to preprocess a source file
src/ArbolRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ArbolRobot.cpp.i
.PHONY : src/ArbolRobot.cpp.i

src/ArbolRobot.s: src/ArbolRobot.cpp.s
.PHONY : src/ArbolRobot.s

# target to generate assembly for a file
src/ArbolRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ArbolRobot.cpp.s
.PHONY : src/ArbolRobot.cpp.s

src/CttesRobot.o: src/CttesRobot.cpp.o
.PHONY : src/CttesRobot.o

# target to build an object file
src/CttesRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/CttesRobot.cpp.o
.PHONY : src/CttesRobot.cpp.o

src/CttesRobot.i: src/CttesRobot.cpp.i
.PHONY : src/CttesRobot.i

# target to preprocess a source file
src/CttesRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/CttesRobot.cpp.i
.PHONY : src/CttesRobot.cpp.i

src/CttesRobot.s: src/CttesRobot.cpp.s
.PHONY : src/CttesRobot.s

# target to generate assembly for a file
src/CttesRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/CttesRobot.cpp.s
.PHONY : src/CttesRobot.cpp.s

src/EvalRobot.o: src/EvalRobot.cpp.o
.PHONY : src/EvalRobot.o

# target to build an object file
src/EvalRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/EvalRobot.cpp.o
.PHONY : src/EvalRobot.cpp.o

src/EvalRobot.i: src/EvalRobot.cpp.i
.PHONY : src/EvalRobot.i

# target to preprocess a source file
src/EvalRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/EvalRobot.cpp.i
.PHONY : src/EvalRobot.cpp.i

src/EvalRobot.s: src/EvalRobot.cpp.s
.PHONY : src/EvalRobot.s

# target to generate assembly for a file
src/EvalRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/EvalRobot.cpp.s
.PHONY : src/EvalRobot.cpp.s

src/FactoryRobot.o: src/FactoryRobot.cpp.o
.PHONY : src/FactoryRobot.o

# target to build an object file
src/FactoryRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/FactoryRobot.cpp.o
.PHONY : src/FactoryRobot.cpp.o

src/FactoryRobot.i: src/FactoryRobot.cpp.i
.PHONY : src/FactoryRobot.i

# target to preprocess a source file
src/FactoryRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/FactoryRobot.cpp.i
.PHONY : src/FactoryRobot.cpp.i

src/FactoryRobot.s: src/FactoryRobot.cpp.s
.PHONY : src/FactoryRobot.s

# target to generate assembly for a file
src/FactoryRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/FactoryRobot.cpp.s
.PHONY : src/FactoryRobot.cpp.s

src/GArbolRobot.o: src/GArbolRobot.cpp.o
.PHONY : src/GArbolRobot.o

# target to build an object file
src/GArbolRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GArbolRobot.cpp.o
.PHONY : src/GArbolRobot.cpp.o

src/GArbolRobot.i: src/GArbolRobot.cpp.i
.PHONY : src/GArbolRobot.i

# target to preprocess a source file
src/GArbolRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GArbolRobot.cpp.i
.PHONY : src/GArbolRobot.cpp.i

src/GArbolRobot.s: src/GArbolRobot.cpp.s
.PHONY : src/GArbolRobot.s

# target to generate assembly for a file
src/GArbolRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GArbolRobot.cpp.s
.PHONY : src/GArbolRobot.cpp.s

src/GirarDer.o: src/GirarDer.cpp.o
.PHONY : src/GirarDer.o

# target to build an object file
src/GirarDer.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarDer.cpp.o
.PHONY : src/GirarDer.cpp.o

src/GirarDer.i: src/GirarDer.cpp.i
.PHONY : src/GirarDer.i

# target to preprocess a source file
src/GirarDer.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarDer.cpp.i
.PHONY : src/GirarDer.cpp.i

src/GirarDer.s: src/GirarDer.cpp.s
.PHONY : src/GirarDer.s

# target to generate assembly for a file
src/GirarDer.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarDer.cpp.s
.PHONY : src/GirarDer.cpp.s

src/GirarIzq.o: src/GirarIzq.cpp.o
.PHONY : src/GirarIzq.o

# target to build an object file
src/GirarIzq.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarIzq.cpp.o
.PHONY : src/GirarIzq.cpp.o

src/GirarIzq.i: src/GirarIzq.cpp.i
.PHONY : src/GirarIzq.i

# target to preprocess a source file
src/GirarIzq.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarIzq.cpp.i
.PHONY : src/GirarIzq.cpp.i

src/GirarIzq.s: src/GirarIzq.cpp.s
.PHONY : src/GirarIzq.s

# target to generate assembly for a file
src/GirarIzq.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/GirarIzq.cpp.s
.PHONY : src/GirarIzq.cpp.s

src/IndRobot.o: src/IndRobot.cpp.o
.PHONY : src/IndRobot.o

# target to build an object file
src/IndRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/IndRobot.cpp.o
.PHONY : src/IndRobot.cpp.o

src/IndRobot.i: src/IndRobot.cpp.i
.PHONY : src/IndRobot.i

# target to preprocess a source file
src/IndRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/IndRobot.cpp.i
.PHONY : src/IndRobot.cpp.i

src/IndRobot.s: src/IndRobot.cpp.s
.PHONY : src/IndRobot.s

# target to generate assembly for a file
src/IndRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/IndRobot.cpp.s
.PHONY : src/IndRobot.cpp.s

src/Mapa.o: src/Mapa.cpp.o
.PHONY : src/Mapa.o

# target to build an object file
src/Mapa.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mapa.cpp.o
.PHONY : src/Mapa.cpp.o

src/Mapa.i: src/Mapa.cpp.i
.PHONY : src/Mapa.i

# target to preprocess a source file
src/Mapa.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mapa.cpp.i
.PHONY : src/Mapa.cpp.i

src/Mapa.s: src/Mapa.cpp.s
.PHONY : src/Mapa.s

# target to generate assembly for a file
src/Mapa.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mapa.cpp.s
.PHONY : src/Mapa.cpp.s

src/Mover.o: src/Mover.cpp.o
.PHONY : src/Mover.o

# target to build an object file
src/Mover.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mover.cpp.o
.PHONY : src/Mover.cpp.o

src/Mover.i: src/Mover.cpp.i
.PHONY : src/Mover.i

# target to preprocess a source file
src/Mover.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mover.cpp.i
.PHONY : src/Mover.cpp.i

src/Mover.s: src/Mover.cpp.s
.PHONY : src/Mover.s

# target to generate assembly for a file
src/Mover.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Mover.cpp.s
.PHONY : src/Mover.cpp.s

src/ObstaculoAdelante.o: src/ObstaculoAdelante.cpp.o
.PHONY : src/ObstaculoAdelante.o

# target to build an object file
src/ObstaculoAdelante.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ObstaculoAdelante.cpp.o
.PHONY : src/ObstaculoAdelante.cpp.o

src/ObstaculoAdelante.i: src/ObstaculoAdelante.cpp.i
.PHONY : src/ObstaculoAdelante.i

# target to preprocess a source file
src/ObstaculoAdelante.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ObstaculoAdelante.cpp.i
.PHONY : src/ObstaculoAdelante.cpp.i

src/ObstaculoAdelante.s: src/ObstaculoAdelante.cpp.s
.PHONY : src/ObstaculoAdelante.s

# target to generate assembly for a file
src/ObstaculoAdelante.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/ObstaculoAdelante.cpp.s
.PHONY : src/ObstaculoAdelante.cpp.s

src/PastoAdelante.o: src/PastoAdelante.cpp.o
.PHONY : src/PastoAdelante.o

# target to build an object file
src/PastoAdelante.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/PastoAdelante.cpp.o
.PHONY : src/PastoAdelante.cpp.o

src/PastoAdelante.i: src/PastoAdelante.cpp.i
.PHONY : src/PastoAdelante.i

# target to preprocess a source file
src/PastoAdelante.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/PastoAdelante.cpp.i
.PHONY : src/PastoAdelante.cpp.i

src/PastoAdelante.s: src/PastoAdelante.cpp.s
.PHONY : src/PastoAdelante.s

# target to generate assembly for a file
src/PastoAdelante.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/PastoAdelante.cpp.s
.PHONY : src/PastoAdelante.cpp.s

src/Robot.o: src/Robot.cpp.o
.PHONY : src/Robot.o

# target to build an object file
src/Robot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Robot.cpp.o
.PHONY : src/Robot.cpp.o

src/Robot.i: src/Robot.cpp.i
.PHONY : src/Robot.i

# target to preprocess a source file
src/Robot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Robot.cpp.i
.PHONY : src/Robot.cpp.i

src/Robot.s: src/Robot.cpp.s
.PHONY : src/Robot.s

# target to generate assembly for a file
src/Robot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Robot.cpp.s
.PHONY : src/Robot.cpp.s

src/Serie.o: src/Serie.cpp.o
.PHONY : src/Serie.o

# target to build an object file
src/Serie.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Serie.cpp.o
.PHONY : src/Serie.cpp.o

src/Serie.i: src/Serie.cpp.i
.PHONY : src/Serie.i

# target to preprocess a source file
src/Serie.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Serie.cpp.i
.PHONY : src/Serie.cpp.i

src/Serie.s: src/Serie.cpp.s
.PHONY : src/Serie.s

# target to generate assembly for a file
src/Serie.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/Serie.cpp.s
.PHONY : src/Serie.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Robot"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/ArbolRobot.o"
	@echo "... src/ArbolRobot.i"
	@echo "... src/ArbolRobot.s"
	@echo "... src/CttesRobot.o"
	@echo "... src/CttesRobot.i"
	@echo "... src/CttesRobot.s"
	@echo "... src/EvalRobot.o"
	@echo "... src/EvalRobot.i"
	@echo "... src/EvalRobot.s"
	@echo "... src/FactoryRobot.o"
	@echo "... src/FactoryRobot.i"
	@echo "... src/FactoryRobot.s"
	@echo "... src/GArbolRobot.o"
	@echo "... src/GArbolRobot.i"
	@echo "... src/GArbolRobot.s"
	@echo "... src/GirarDer.o"
	@echo "... src/GirarDer.i"
	@echo "... src/GirarDer.s"
	@echo "... src/GirarIzq.o"
	@echo "... src/GirarIzq.i"
	@echo "... src/GirarIzq.s"
	@echo "... src/IndRobot.o"
	@echo "... src/IndRobot.i"
	@echo "... src/IndRobot.s"
	@echo "... src/Mapa.o"
	@echo "... src/Mapa.i"
	@echo "... src/Mapa.s"
	@echo "... src/Mover.o"
	@echo "... src/Mover.i"
	@echo "... src/Mover.s"
	@echo "... src/ObstaculoAdelante.o"
	@echo "... src/ObstaculoAdelante.i"
	@echo "... src/ObstaculoAdelante.s"
	@echo "... src/PastoAdelante.o"
	@echo "... src/PastoAdelante.i"
	@echo "... src/PastoAdelante.s"
	@echo "... src/Robot.o"
	@echo "... src/Robot.i"
	@echo "... src/Robot.s"
	@echo "... src/Serie.o"
	@echo "... src/Serie.i"
	@echo "... src/Serie.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

