# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/luisremis/Google Drive/Code/Robot/Robot"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/luisremis/Google Drive/Code/Robot/Robot"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/luisremis/Google Drive/Code/Robot/Robot/CMakeFiles" "/Users/luisremis/Google Drive/Code/Robot/Robot/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/luisremis/Google Drive/Code/Robot/Robot/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Robot

# Build rule for target.
Robot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Robot
.PHONY : Robot

# fast build rule for target.
Robot/fast:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/build
.PHONY : Robot/fast

ArbolRobot.o: ArbolRobot.cpp.o
.PHONY : ArbolRobot.o

# target to build an object file
ArbolRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ArbolRobot.cpp.o
.PHONY : ArbolRobot.cpp.o

ArbolRobot.i: ArbolRobot.cpp.i
.PHONY : ArbolRobot.i

# target to preprocess a source file
ArbolRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ArbolRobot.cpp.i
.PHONY : ArbolRobot.cpp.i

ArbolRobot.s: ArbolRobot.cpp.s
.PHONY : ArbolRobot.s

# target to generate assembly for a file
ArbolRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ArbolRobot.cpp.s
.PHONY : ArbolRobot.cpp.s

CttesRobot.o: CttesRobot.cpp.o
.PHONY : CttesRobot.o

# target to build an object file
CttesRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/CttesRobot.cpp.o
.PHONY : CttesRobot.cpp.o

CttesRobot.i: CttesRobot.cpp.i
.PHONY : CttesRobot.i

# target to preprocess a source file
CttesRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/CttesRobot.cpp.i
.PHONY : CttesRobot.cpp.i

CttesRobot.s: CttesRobot.cpp.s
.PHONY : CttesRobot.s

# target to generate assembly for a file
CttesRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/CttesRobot.cpp.s
.PHONY : CttesRobot.cpp.s

EvalRobot.o: EvalRobot.cpp.o
.PHONY : EvalRobot.o

# target to build an object file
EvalRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/EvalRobot.cpp.o
.PHONY : EvalRobot.cpp.o

EvalRobot.i: EvalRobot.cpp.i
.PHONY : EvalRobot.i

# target to preprocess a source file
EvalRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/EvalRobot.cpp.i
.PHONY : EvalRobot.cpp.i

EvalRobot.s: EvalRobot.cpp.s
.PHONY : EvalRobot.s

# target to generate assembly for a file
EvalRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/EvalRobot.cpp.s
.PHONY : EvalRobot.cpp.s

FactoryRobot.o: FactoryRobot.cpp.o
.PHONY : FactoryRobot.o

# target to build an object file
FactoryRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/FactoryRobot.cpp.o
.PHONY : FactoryRobot.cpp.o

FactoryRobot.i: FactoryRobot.cpp.i
.PHONY : FactoryRobot.i

# target to preprocess a source file
FactoryRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/FactoryRobot.cpp.i
.PHONY : FactoryRobot.cpp.i

FactoryRobot.s: FactoryRobot.cpp.s
.PHONY : FactoryRobot.s

# target to generate assembly for a file
FactoryRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/FactoryRobot.cpp.s
.PHONY : FactoryRobot.cpp.s

GArbolRobot.o: GArbolRobot.cpp.o
.PHONY : GArbolRobot.o

# target to build an object file
GArbolRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GArbolRobot.cpp.o
.PHONY : GArbolRobot.cpp.o

GArbolRobot.i: GArbolRobot.cpp.i
.PHONY : GArbolRobot.i

# target to preprocess a source file
GArbolRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GArbolRobot.cpp.i
.PHONY : GArbolRobot.cpp.i

GArbolRobot.s: GArbolRobot.cpp.s
.PHONY : GArbolRobot.s

# target to generate assembly for a file
GArbolRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GArbolRobot.cpp.s
.PHONY : GArbolRobot.cpp.s

GirarDer.o: GirarDer.cpp.o
.PHONY : GirarDer.o

# target to build an object file
GirarDer.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarDer.cpp.o
.PHONY : GirarDer.cpp.o

GirarDer.i: GirarDer.cpp.i
.PHONY : GirarDer.i

# target to preprocess a source file
GirarDer.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarDer.cpp.i
.PHONY : GirarDer.cpp.i

GirarDer.s: GirarDer.cpp.s
.PHONY : GirarDer.s

# target to generate assembly for a file
GirarDer.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarDer.cpp.s
.PHONY : GirarDer.cpp.s

GirarIzq.o: GirarIzq.cpp.o
.PHONY : GirarIzq.o

# target to build an object file
GirarIzq.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarIzq.cpp.o
.PHONY : GirarIzq.cpp.o

GirarIzq.i: GirarIzq.cpp.i
.PHONY : GirarIzq.i

# target to preprocess a source file
GirarIzq.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarIzq.cpp.i
.PHONY : GirarIzq.cpp.i

GirarIzq.s: GirarIzq.cpp.s
.PHONY : GirarIzq.s

# target to generate assembly for a file
GirarIzq.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/GirarIzq.cpp.s
.PHONY : GirarIzq.cpp.s

IndRobot.o: IndRobot.cpp.o
.PHONY : IndRobot.o

# target to build an object file
IndRobot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/IndRobot.cpp.o
.PHONY : IndRobot.cpp.o

IndRobot.i: IndRobot.cpp.i
.PHONY : IndRobot.i

# target to preprocess a source file
IndRobot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/IndRobot.cpp.i
.PHONY : IndRobot.cpp.i

IndRobot.s: IndRobot.cpp.s
.PHONY : IndRobot.s

# target to generate assembly for a file
IndRobot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/IndRobot.cpp.s
.PHONY : IndRobot.cpp.s

Mapa.o: Mapa.cpp.o
.PHONY : Mapa.o

# target to build an object file
Mapa.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mapa.cpp.o
.PHONY : Mapa.cpp.o

Mapa.i: Mapa.cpp.i
.PHONY : Mapa.i

# target to preprocess a source file
Mapa.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mapa.cpp.i
.PHONY : Mapa.cpp.i

Mapa.s: Mapa.cpp.s
.PHONY : Mapa.s

# target to generate assembly for a file
Mapa.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mapa.cpp.s
.PHONY : Mapa.cpp.s

Mover.o: Mover.cpp.o
.PHONY : Mover.o

# target to build an object file
Mover.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mover.cpp.o
.PHONY : Mover.cpp.o

Mover.i: Mover.cpp.i
.PHONY : Mover.i

# target to preprocess a source file
Mover.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mover.cpp.i
.PHONY : Mover.cpp.i

Mover.s: Mover.cpp.s
.PHONY : Mover.s

# target to generate assembly for a file
Mover.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Mover.cpp.s
.PHONY : Mover.cpp.s

ObstaculoAdelante.o: ObstaculoAdelante.cpp.o
.PHONY : ObstaculoAdelante.o

# target to build an object file
ObstaculoAdelante.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ObstaculoAdelante.cpp.o
.PHONY : ObstaculoAdelante.cpp.o

ObstaculoAdelante.i: ObstaculoAdelante.cpp.i
.PHONY : ObstaculoAdelante.i

# target to preprocess a source file
ObstaculoAdelante.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ObstaculoAdelante.cpp.i
.PHONY : ObstaculoAdelante.cpp.i

ObstaculoAdelante.s: ObstaculoAdelante.cpp.s
.PHONY : ObstaculoAdelante.s

# target to generate assembly for a file
ObstaculoAdelante.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/ObstaculoAdelante.cpp.s
.PHONY : ObstaculoAdelante.cpp.s

PastoAdelante.o: PastoAdelante.cpp.o
.PHONY : PastoAdelante.o

# target to build an object file
PastoAdelante.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/PastoAdelante.cpp.o
.PHONY : PastoAdelante.cpp.o

PastoAdelante.i: PastoAdelante.cpp.i
.PHONY : PastoAdelante.i

# target to preprocess a source file
PastoAdelante.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/PastoAdelante.cpp.i
.PHONY : PastoAdelante.cpp.i

PastoAdelante.s: PastoAdelante.cpp.s
.PHONY : PastoAdelante.s

# target to generate assembly for a file
PastoAdelante.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/PastoAdelante.cpp.s
.PHONY : PastoAdelante.cpp.s

Robot.o: Robot.cpp.o
.PHONY : Robot.o

# target to build an object file
Robot.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Robot.cpp.o
.PHONY : Robot.cpp.o

Robot.i: Robot.cpp.i
.PHONY : Robot.i

# target to preprocess a source file
Robot.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Robot.cpp.i
.PHONY : Robot.cpp.i

Robot.s: Robot.cpp.s
.PHONY : Robot.s

# target to generate assembly for a file
Robot.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Robot.cpp.s
.PHONY : Robot.cpp.s

Serie.o: Serie.cpp.o
.PHONY : Serie.o

# target to build an object file
Serie.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Serie.cpp.o
.PHONY : Serie.cpp.o

Serie.i: Serie.cpp.i
.PHONY : Serie.i

# target to preprocess a source file
Serie.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Serie.cpp.i
.PHONY : Serie.cpp.i

Serie.s: Serie.cpp.s
.PHONY : Serie.s

# target to generate assembly for a file
Serie.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/Serie.cpp.s
.PHONY : Serie.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Robot.dir/build.make CMakeFiles/Robot.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Robot"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ArbolRobot.o"
	@echo "... ArbolRobot.i"
	@echo "... ArbolRobot.s"
	@echo "... CttesRobot.o"
	@echo "... CttesRobot.i"
	@echo "... CttesRobot.s"
	@echo "... EvalRobot.o"
	@echo "... EvalRobot.i"
	@echo "... EvalRobot.s"
	@echo "... FactoryRobot.o"
	@echo "... FactoryRobot.i"
	@echo "... FactoryRobot.s"
	@echo "... GArbolRobot.o"
	@echo "... GArbolRobot.i"
	@echo "... GArbolRobot.s"
	@echo "... GirarDer.o"
	@echo "... GirarDer.i"
	@echo "... GirarDer.s"
	@echo "... GirarIzq.o"
	@echo "... GirarIzq.i"
	@echo "... GirarIzq.s"
	@echo "... IndRobot.o"
	@echo "... IndRobot.i"
	@echo "... IndRobot.s"
	@echo "... Mapa.o"
	@echo "... Mapa.i"
	@echo "... Mapa.s"
	@echo "... Mover.o"
	@echo "... Mover.i"
	@echo "... Mover.s"
	@echo "... ObstaculoAdelante.o"
	@echo "... ObstaculoAdelante.i"
	@echo "... ObstaculoAdelante.s"
	@echo "... PastoAdelante.o"
	@echo "... PastoAdelante.i"
	@echo "... PastoAdelante.s"
	@echo "... Robot.o"
	@echo "... Robot.i"
	@echo "... Robot.s"
	@echo "... Serie.o"
	@echo "... Serie.i"
	@echo "... Serie.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

